Fix NFR upgrade test
Problem:
NFR performance test fails with the following error:
Error: INSTALLATION FAILED: release name "": no name provided

Solution:
Fix the test by providing the release name.
Also, add a missing nfr config setting.

CLOSES https://github.com/nginxinc/nginx-gateway-fabric/issues/1715

Testing:
- Ran upgrade test successfully